Reduce scope to hopefully avoid spawn bug
Sometime in test I get a panic from Crossbeam scope because
EWOULDBLK.  Can't find anyone else have this problem.  Maybe
reducing the size of scope will help.

(I get an OOM error now.  So, improvement?)

Error was:

running 1 test
words: 1  lines: 10343000
LogFile { bytes: 51714985, lines: 1149287 }
>> 5
>> 50
>> 95
thread 'tests::file_parse_lines_bytes' panicked at 'assertion failed: `(left == right)`
  left: `50`,
 right: `10`', indexed_file/src/lib.rs:101:13
stack backtrace:
   0: rust_begin_unwind

running 1 test
words: 5  lines: 413000
thread 'tests::file_parse_lines_bytes' panicked at 'failed to spawn scoped thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /home/phord/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.8/src/thread.rs:253:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: core::result::Result<T,E>::expect
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1022:23
   4: crossbeam_utils::thread::Scope::spawn
             at /home/phord/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.8/src/thread.rs:251:9
   5: indexed_file::indexer::LogFile::index_file::{{closure}}
             at ./indexed_file/src/indexer.rs:366:17
   6: crossbeam_utils::thread::scope::{{closure}}
             at /home/phord/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.8/src/thread.rs:160:65
   7: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:271:9
   8: std::panicking::try::do_call
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
   9: __rust_try
  10: std::panicking::try
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  11: std::panic::catch_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  12: crossbeam_utils::thread::scope
             at /home/phord/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.8.8/src/thread.rs:160:18
  13: indexed_file::indexer::LogFile::index_file
             at ./indexed_file/src/indexer.rs:347:9
  14: indexed_file::indexer::LogFile::test_new
             at ./indexed_file/src/indexer.rs:338:9
  15: indexed_file::tests::file_parse_lines_bytes
             at ./indexed_file/src/lib.rs:81:20
  16: indexed_file::tests::file_parse_lines_bytes::{{closure}}
             at ./indexed_file/src/lib.rs:67:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
  18: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.